apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viewsense-dev
resources:
  - namespace.yaml
  - service-accounts.yaml
  - data.yaml
  - applications.yaml
  - network-policies.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: viewsense
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
